### ISSUE TITLE
Compiler error on compiling samples from sandbox

### ISSUE THREAD

**Issue by rdlester** [himura/twitter-conduit#31]
I get a sequence of compiler errors when trying to build this project from a fresh cabal sandbox.

First, the samples are missing a dependency on `scotty`. Running `cabal install scotty` fixes this.

Then, the compiler throws two "not in scope" errors from userstream.hs for `^!` and `act`.

**Comment by himura** [comment]
The document lack some instruction(b485bac80630f1eb7540ce4ee89b999ec758f6c2), so you may solve the former problem by `cabal install --only-dependencies -fbuild-samples`.

The latter probrem is caused by a splitting of lens package at version 4.7.
Both `^!` and `act` functions are moved into [lens-action](http://hackage.haskell.org/package/lens-action) package.
However, the `userstream.hs` does not required those function because they are redundant. I've just removed that code in a594e6b2a6df1a1608d2d16614865085be43258e.

**Comment by rdlester** [comment]
Yep. That seems to have fixed it. Thanks.
